### ISSUE TITLE
no top level LICENSE file, suggest MIT license

### ISSUE THREAD

**Issue by MarkAtwood** [nuclearsandwich/workspace#12]
There is no top level LICENSE file
The MIT license makes sense for a project like this.

**Comment by nuclearsandwich** [comment]
Like other ROS 2 projects, this one uses the Apache 2 license. https://github.com/ros2/ros_workspace/blob/a94dc0abfb8e750632a4a365a534797feb25786d/package.xml#L10

This project could use a license file but it's not strictly necessary.

**Comment by MarkAtwood** [comment]
Thank you!
