### ISSUE TITLE
Providing default environment hooks for third party packages

### ISSUE THREAD

**Issue by nuclearsandwich** [nuclearsandwich/workspace#7]
Currently, there are a number of packages in ROS 2 which are built from sources outside our control. These packages still install themselves into the ROS prefix (`/opt/ros/$ROS_DISTRO/`) but don't provide any environment hooks to ensure that their executables are put onto PATH and their libraries are added to LD_LIBRARY_PATH, or other platform equivalents.

To overcome this issue for debian packages in early releases of ROS 2, this workspace package added some environment hooks unconditionally putting the necessary paths on LD_LIBRARY_PATH.

Packages benefiting from these hooks in ROS 2 bouncy (packages which have shared libraries in /opt/ros/bouncy/lib but no environment hook setting up the library path for themselves)

* ros-bouncy-console-bridge
* ros-bouncy-examples-rclcpp-minimal-composition
* ros-bouncy-fastcdr
* ros-bouncy-fastrtps
* ros-bouncy-orocos-kdl
* ros-bouncy-osrf-testing-tools-cpp
* ros-bouncy-rclpy
* ros-bouncy-resource-retriever
* ros-bouncy-rviz-common
* ros-bouncy-rviz-default-plugins
* ros-bouncy-rviz-rendering
* ros-bouncy-urdfdom

Some of these packages are ours and we should determine whether setting hooks for them is needed.

A number of packages that have needed this treatment are moving into  `_vendor` packages which would potentially be a better home for these hooks.

For the remaining packages and future packages that can't provide their own hooks, is it worth populating the workspace with hooks for the default executable and binary paths so that no matter what further packages are installed the ROS prefix is usable?

**Comment by mikaelarguedas** [comment]
@ros2/team Please take a look

**Comment by tfoote** [comment]
It does make sense to make sure that any of these core dependencies work. But in general we should try to minimize the set of packages that require this and try to push as many of them to be self contained as possible. Even if it means release repo patches.

**Comment by nuclearsandwich** [comment]
We discussed in Tuesday's meeting that setting up the environment with some expected defaults like `bin` in PATH and `lib` in LD_LIBRARY_PATH is desired for a streamlined user experience with third party packages. But that the packages we own should be updated so that they provide their own environment hooks.

Using the list above minus third party packages, I'll open PRs setting the hooks as needed targeting Crystal.
